FROM python:3.11-slim
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && pip install --no-cache-dir pytest

COPY src ./src
COPY tests ./tests

RUN mkdir -p /app/reports
CMD ["pytest","-q","--junitxml=/app/reports/test-results.xml"]
