apiVersion: batch/v1
kind: Job
metadata:
  name: k6
  namespace: arvmldevopspipeline
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: k6
          image: grafana/k6:latest
          args: ["run", "/scripts/k6.js"]
          env:
            - name: BASE_URL
              value: "http://arvmldevopspipeline-svc.arvmldevopspipeline.svc.cluster.local:8000"
          volumeMounts:
            - name: k6-scripts
              mountPath: /scripts
      volumes:
        - name: k6-scripts
          configMap:
            name: k6-script
